### ISSUE TITLE
想问一下数据集下载的问题

### ISSUE THREAD

**Issue by Rel-pcy** [zju-muslab/AdvReverb#1]
您好，我是一名在校大学生，目前正在尝试复现这篇论文，但是数据集下载和与data里几个csv文件对应问题感觉比较麻烦，想问一下，可以求一下数据集吗，其中一个就可以。

**Comment by Rel-pcy** [comment]
已经解决，自己找找数据集，写个文件处理一下

**Comment by zju-muslab** [comment]
👍👍👍

**Comment by Lotus46** [comment]
> 已经解决，自己找找数据集，写个文件处理一下
您好，我也遇到了相同的问题，想请教一下您解决的具体方法

**Comment by Rel-pcy** [comment]
Real_pcy
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zju-muslab/AdvReverb"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月19日(星期四) 上午10:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zju-muslab/AdvReverb] 想问一下数据集下载的问题 (Issue #1)





  
已经解决，自己找找数据集，写个文件处理一下
 您好，我也遇到了相同的问题，想请教一下您解决的具体方法

**Comment by Lotus46** [comment]
您好，我这边看到您发的消息是这样的


不知道是不是消息被加密了，不知您是否方便将联系方式告知我。




敖武
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zju-muslab/AdvReverb"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月19日(星期四) 上午10:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zju-muslab/AdvReverb] 想问一下数据集下载的问题 (Issue #1)





Real_pcy
***@***.***



&amp;nbsp;




------------------&amp;nbsp;原始邮件&amp;nbsp;------------------
发件人:                                                                                                                        "zju-muslab/AdvReverb"                                                                                    ***@***.***&amp;gt;;
发送时间:&amp;nbsp;2024年9月19日(星期四) 上午10:12
***@***.***&amp;gt;;
***@***.******@***.***&amp;gt;;
主题:&amp;nbsp;Re: [zju-muslab/AdvReverb] 想问一下数据集下载的问题 (Issue #1)





  
已经解决，自己找找数据集，写个文件处理一下
 您好，我也遇到了相同的问题，想请教一下您解决的具体方法

**Comment by Rel-pcy** [comment]
刚刚看到消息，附件里没有吗？可以添加微信：ttxysml053846




Real_pcy
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zju-muslab/AdvReverb"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月19日(星期四) 中午11:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zju-muslab/AdvReverb] 想问一下数据集下载的问题 (Issue #1)





 您好，我这边看到您发的消息是这样的 
 
 
 不知道是不是消息被加密了，不知您是否方便将联系方式告知我。 
 
 
 
 
 敖武 
 ***@***.*** 
 
 
 
 &amp;nbsp; 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "zju-muslab/AdvReverb"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2024年9月19日(星期四) 上午10:40 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [zju-muslab/AdvReverb] 想问一下数据集下载的问题 (Issue #1) 
 
 
 
 
 
 Real_pcy 
 ***@***.*** 
 
 
 
 &amp;amp;nbsp; 
 
 
 
 
 ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------ 
 发件人:                                                                                                                        "zju-muslab/AdvReverb"                                                                                    ***@***.***&amp;amp;gt;; 
 发送时间:&amp;amp;nbsp;2024年9月19日(星期四) 上午10:12 
 ***@***.***&amp;amp;gt;; 
 ***@***.******@***.***&amp;amp;gt;; 
 主题:&amp;amp;nbsp;Re: [zju-muslab/AdvReverb] 想问一下数据集下载的问题 (Issue #1) 
 
 
 
 
 
    
 已经解决，自己找找数据集，写个文件处理一下 
  您好，我也遇到了相同的问题，想请教一下您解决的具体方法

**Comment by MarkGoyens** [comment]
> 已经解决，自己找找数据集，写个文件处理一下

您好，我也遇到了关于数据集的相同的问题，想请教一下您解决的具体方法

**Comment by Rel-pcy** [comment]
您好，我找到了当时的实验报告，把这部分复制下来了，不知道这个可以解决您的问题吗？


Real_pcy
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zju-muslab/AdvReverb"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2025年3月7日(星期五) 下午5:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zju-muslab/AdvReverb] 想问一下数据集下载的问题 (Issue #1)



    
已经解决，自己找找数据集，写个文件处理一下
  
您好，我也遇到了关于数据集的相同的问题，想请教一下您解决的具体方法

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;
  MarkGoyens left a comment (zju-muslab/AdvReverb#1)
  
已经解决，自己找找数据集，写个文件处理一下
  
您好，我也遇到了关于数据集的相同的问题，想请教一下您解决的具体方法

**Comment by MarkGoyens** [comment]
您好，我这边收到了您的邮件回信，但是是被屏蔽掉的，方便加一下您的联系方式吗

**Comment by MarkGoyens** [comment]
您好，我这边收到了您的邮件回信，但是邮件内容是被屏蔽掉的，方便加一下您的联系方式吗

**Comment by Rel-pcy** [comment]
794675206不知道能看见吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2025年3月10日(周一) 下午4:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zju-muslab/AdvReverb] 想问一下数据集下载的问题 (Issue #1)


   
您好，我这边收到了您的邮件回信，但是邮件内容是被屏蔽掉的，方便加一下您的联系方式吗

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;
  MarkGoyens left a comment (zju-muslab/AdvReverb#1)
 
您好，我这边收到了您的邮件回信，但是邮件内容是被屏蔽掉的，方便加一下您的联系方式吗
